### ISSUE TITLE
Default deserialize option will fail on a string value?

### ISSUE THREAD

**Issue by AjaxSolutions** [jotaijs/jotai-location#19]
If `options.deserialize` is not provided, JSON.parse will fail on a string value.  This is probably not intended?

 ` const deserialize = options?.deserialize || JSON.parse;`

**Comment by dai-shi** [comment]
Why so? You should provide proper serialize/deserialize. JSON.serialize/parse is a hacky solution without validation, but handy.

**Comment by AjaxSolutions** [comment]
Thanks.

**Comment by AjaxSolutions** [comment]
Thanks
