### ISSUE TITLE
Prevent syntax error in atomWithHash

### ISSUE THREAD

**Issue by h-evers** [jotaijs/jotai-location#21]
I wonder if it is possible to prevent the syntax error inducted when calling a page that uses "atomWithHash" with an "invalid" search term. It occurs at the time of importing (well, kind of) and i cannot think of a method to prevent this. Sorry for not being a React pro...
The example would be: https://et5pld.csb.app/#count=asd2

> SyntaxError
> Unexpected token 'a', "asd2" is not valid JSON

**Comment by dai-shi** [comment]
Can you pass `deserialize` option and recover from error? The default is `JSON.parse` which can throw and not type safe. We should suggest avoiding the default one for practical use case.

**Comment by h-evers** [comment]
Yes, that actually works. Didn't realize this option - although it is mentioned in the documentary. Maybe the default is not great, but may be enough for most of the time.

**Comment by dai-shi** [comment]
On second thought, recovering error would be great for the default one too. Let me draft a PR.
